version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - unconvert
    - bodyclose
    - errname
    - errorlint

  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*encoding/json.Encoder).Encode
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - ifElseChain
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
