// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Preference struct {
	ID           int64
	Profile      string
	LastPgmPath  string
	LastWavPath  string
	AuditionMode string
}
