// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getPreferences = `-- name: GetPreferences :one
SELECT profile, last_pgm_path, last_wav_path, audition_mode
FROM preferences WHERE id = 1
`

type GetPreferencesRow struct {
	Profile      string
	LastPgmPath  string
	LastWavPath  string
	AuditionMode string
}

func (q *Queries) GetPreferences(ctx context.Context) (GetPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getPreferences)
	var i GetPreferencesRow
	err := row.Scan(
		&i.Profile,
		&i.LastPgmPath,
		&i.LastWavPath,
		&i.AuditionMode,
	)
	return i, err
}

const updateAllPreferences = `-- name: UpdateAllPreferences :exec
UPDATE preferences SET profile = ?, last_pgm_path = ?, last_wav_path = ?, audition_mode = ?
WHERE id = 1
`

type UpdateAllPreferencesParams struct {
	Profile      string
	LastPgmPath  string
	LastWavPath  string
	AuditionMode string
}

func (q *Queries) UpdateAllPreferences(ctx context.Context, arg UpdateAllPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateAllPreferences,
		arg.Profile,
		arg.LastPgmPath,
		arg.LastWavPath,
		arg.AuditionMode,
	)
	return err
}

const updateAuditionMode = `-- name: UpdateAuditionMode :exec
UPDATE preferences SET audition_mode = ? WHERE id = 1
`

func (q *Queries) UpdateAuditionMode(ctx context.Context, auditionMode string) error {
	_, err := q.db.ExecContext(ctx, updateAuditionMode, auditionMode)
	return err
}

const updateLastPGMPath = `-- name: UpdateLastPGMPath :exec
UPDATE preferences SET last_pgm_path = ? WHERE id = 1
`

func (q *Queries) UpdateLastPGMPath(ctx context.Context, lastPgmPath string) error {
	_, err := q.db.ExecContext(ctx, updateLastPGMPath, lastPgmPath)
	return err
}

const updateLastWAVPath = `-- name: UpdateLastWAVPath :exec
UPDATE preferences SET last_wav_path = ? WHERE id = 1
`

func (q *Queries) UpdateLastWAVPath(ctx context.Context, lastWavPath string) error {
	_, err := q.db.ExecContext(ctx, updateLastWAVPath, lastWavPath)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE preferences SET profile = ? WHERE id = 1
`

func (q *Queries) UpdateProfile(ctx context.Context, profile string) error {
	_, err := q.db.ExecContext(ctx, updateProfile, profile)
	return err
}
